title: shecannotsee
author: shecannotsee
email: shecannotsee@163.com
url: https://shecannotsee.github.io
baseurl: ""
lang: zh-CN
description: >
  关于 C++、Linux、构建系统、工程实践与个人项目的长期技术记录。

permalink: /:slug.html

favicon: "logo.png"

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light"
  back_home_text: "/home"
  date_format: "%Y-%m-%d"
  show_description: false

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
